controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: forward_command_controller/ForwardCommandController

    position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  ros__parameters:
    joints:
      - pan_joint
    interface_name: position

velocity_controller:
  ros__parameters:
    joints:
      - pan_joint
    interface_name: velocity